name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Build and push the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASS }}
      run: |
        echo $DOCKER_USERNAME
        Build_timestamp=$(date +%s)
        docker build . --file Dockerfile -t $DOCKER_USERNAME/github_test:$Build_timestamp
        docker tag $DOCKER_USERNAME/github_test:$Build_timestamp $DOCKER_USERNAME/github_test:latest
        docker login docker.io --username $DOCKER_USERNAME --password DOCKER_PASSWORD
        docker push $DOCKER_USERNAME/github_test:latest
