name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Build and push the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASS }}
        BUILD_TIME: $(date +%s)
      run: |
        echo $DOCKER_USERNAME
        echo $(date +%s)
        echo $BUILD_TIME

        docker build . --file Dockerfile -t $DOCKER_USERNAME/github_test:$BUILD_TIME
        docker login docker.com --username $DOCKER_USERNAME --password DOCKER_PASSWORD
        docker tag $DOCKER_USERNAME/github_test:$BUILD_TIME $DOCKER_USERNAME/github_test:latest
        docker push $DOCKER_USERNAME/github_test:latest
